repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --args=--recursive
  - repo: local
    hooks:
      - id: terraform_docs
        name: terraform_docs
        entry: bash -c 'make tfdocs && git add "docs/README.md" && git add $(find modules -type f -name README.md)'
        language: system
        types: [terraform]
        pass_filenames: false
